### ISSUE TITLE
Concat in the same order

### ISSUE THREAD

**Issue by TomMalbran** [smiclea/brackets-js-concat#5]
I would like to have an option where it will print the files in the output in the same order as they are in the list. This is because I would need to have jquery before my script so that it works.

```
concatOnSave = true;
output = build.js;
minify = false;
-scripts/jquery.js;
-scripts/jquery-ui.js;
-scripts/main.js;
```

In the file scripts/main.js I am using $ as if it was already loaded, but as it is printed before jquery.js when building it, it doesn't work. Notice that main.js is a really tiny file, and it makes sense that it resolves before than jquery.

**Comment by pieter-biesemans** [comment]
Try wrapping your main.js in a $('document').ready(function(){});
This should make it wait until the full document is loaded, including all JS.
